name: Deploy Xom Appétit Frontend

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: Xomware/github-actions/.github/workflows/deploy-frontend-s3.yml@feature/nextjs-upload
    with:
      app: meals
      ssm: |
        NEXT_PUBLIC_COGNITO_USER_POOL_ID=/xomware/shared/cognito/user-pool-id
        NEXT_PUBLIC_COGNITO_CLIENT_ID=/xomware/shared/cognito/clients/xomappetit-id
        NEXT_PUBLIC_COGNITO_DOMAIN=/xomware/shared/cognito/hosted-ui-domain
        NEXT_PUBLIC_USERS_API_URL=/xomware/shared/users-api/url
        NEXT_PUBLIC_AVATARS_CDN_URL=/xomware/shared/avatars/cdn-url
      build-command: |
        export NEXT_PUBLIC_API_URL=https://api.xomappetit.xomware.com
        export NEXT_PUBLIC_AWS_REGION=us-east-1
        npm run build
      dist-dir: out
      bucket: xomappetit.xomware.com
      domain: xomappetit.xomware.com
      nextjs: true
